name: Java CI (Tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Criar application-test.properties
        run: |
          mkdir -p src/test/resources
          cat <<EOF > src/test/resources/application-test.properties
          spring.application.name=server

          geoapify.api.key=${GEOAPIFY_API_KEY}

          spring.datasource.url=jdbc:h2:mem:testdb
          spring.datasource.driver-class-name=org.h2.Driver
          spring.datasource.username=sa
          spring.datasource.password=password

          spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
          spring.jpa.hibernate.ddl-auto=update

          jwt.secret=${JWT_SECRET}
          mongodb.atlas.uri=${MONGO_URI}
          mongodb.atlas.database=${DATABASE_NAME}
          EOF
        env:
          GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_URI: ${{secrets.MONGO_URI}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}

      - name: Rodar build e testes
        run: mvn -B clean verify -Dtest='!CollegeImageTest'
        env:
          SPRING_PROFILES_ACTIVE: test